# Generated by Django 5.1.6 on 2025-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
